on:
  push:
    paths:
      - 'dev/**'
      # - 'srinath/**'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
        # Build App and Run Application Test
      # - name: Run unit Test
        # run: node index.js
        # run: python dns.py